query FindSomeLetters {
  allLetters(
    _size: 5
    _cursor: "2DOB2DRyMjkxNDk4MTMzODU5MzQxODMygWZMZXR0ZXKBZ2NsYXNzZXOAgICA"
  ) {
    data {
      _id
      letter
    }
    before
    after
  }
}
